name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Package Application
      run: zip -r deploy.zip .

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'  # Specify your region
      run: |
        pip install awsebcli --upgrade --user
        eb init -p node.js your-application-name --region $AWS_REGION
        eb deploy
